name: Build and Release # name it whatever you like
on:
  push:
    tags:
      - "registry-v*" # triggered whenever a new tag (prefixed with "v") is pushed to the repository

permissions: # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract-a:
    uses: ./.github/workflows/actions/release-contract.yml@feat/guarded_registry
    with:
      release_name: ${{ github.ref_name }} # use git tag as unique release name
      release_description: "Contract release" # some boring placeholder text to attach
      home_domain: "theaha.co" # home domain for the contract
      # relative_path: '["contracts/registry"]' # relative path to your really awesome contract
      package: "registry" # package name to build
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }} # don't modify this line
