name: rust

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "website/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CI_BUILD: "--locked"
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup update
      - run: rustup target add wasm32v1-none
      - run: rustup component add rustfmt clippy
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config libudev-dev
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@just
      - uses: cargo-bins/cargo-binstall@main
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - uses: stellar/stellar-cli@v25.1.0
      - name: build since clippy needs contracts to be built
        run: just build
      - name: Run cargo clippy
        run: just clippy
      - name: Run cargo clippy on tests
        run: just clippy-test
      - name: Unit Tests
        run: just test
